CREATE TABLE USUARIO ( 
    ID NUMBER(12) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
	NOME VARCHAR2(100) NOT NULL,
	SEXO CHAR(1) NOT NULL,
    NASCIMENTO DATE NOT NULL,
	SENHA VARCHAR(200) NOT NULL, 	
    CONSTRAINT USUARIO_PK PRIMARY KEY (ID)
);

ALTER TABLE USUARIO
ADD CONSTRAINT EMAIL_UNIQUE UNIQUE (EMAIL);

CREATE TABLE SOLICITACAO(
	IDSOLICITANTE NUMBER(12) NOT NULL,
	IDRECEPTOR NUMBER(12) NOT NULL,
	FOREIGN KEY(IDSOLICITANTE) REFERENCES USUARIO (ID),
	FOREIGN KEY(IDRECEPTOR) REFERENCES USUARIO (ID)
);

CREATE TABLE AMIZADE(
	IDUSUARIO NUMBER(12) NOT NULL,
	IDAMIGO NUMBER(12) NOT NULL,
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO (ID),
	FOREIGN KEY(IDAMIGO) REFERENCES USUARIO (ID)
);

CREATE TABLE POST(
	ID NUMBER (12) NOT NULL,
	IDUSUARIO NUMBER(12) NOT NULL,
	TEXTO VARCHAR2(300) NOT NULL,
	DATAPOST DATE NOT NULL,
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO (ID),	
	CONSTRAINT POST_PK PRIMARY KEY (ID)
);

CREATE TABLE CURTIDA(
	IDPOST NUMBER (12) NOT NULL,
	IDUSUARIO NUMBER(12) NOT NULL,
	FOREIGN KEY(IDPOST) REFERENCES POST (ID),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO (ID)
);

CREATE TABLE COMENTARIO(
	IDPOST NUMBER (12) NOT NULL,
	IDUSUARIO NUMBER(12) NOT NULL,
	TEXTO VARCHAR2(300) NOT NULL,
	DATACOMENTARIO DATE NOT NULL,
	FOREIGN KEY(IDPOST) REFERENCES POST (ID),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO (ID)
);

CREATE SEQUENCE SEQ_USUARIO  
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;

CREATE SEQUENCE SEQ_POST  
    MINVALUE 1 
    MAXVALUE 999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER  
    NOCYCLE;